version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=managerleague
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
